### ISSUE TITLE
Slow and Lagging on CollectionView or TableView

### ISSUE THREAD

**Issue by BilalReffas** [Yalantis/ForceBlur#4]
When I am using a CollectionView and apply the effect the scrollview will be slow. Because of setting it again and again which is normal and not good for the performance. 
But how I can add a ContainerView so I don't have to apply the effect constantly ? :)

**Comment by serejahh** [comment]
Hi @BilalReffas. The component was initially implemented via UIVisualEffectView + mask. But there's a bug on iOS 10 and the mask cannot be applied to UIVisualEffectView, so we had to replace it with a naive and not so good approach

**Comment by serejahh** [comment]
Duplication of #2
