### ISSUE TITLE
Slow loading when setting image

### ISSUE THREAD

**Issue by asimonv** [Yalantis/ForceBlur#6]
It takes more than 1 second to load the image when I set it. 
Tested on iPhone 6.

Edit: it happens when you use a big size image (700Kb for example).

**Comment by serejahh** [comment]
I believe it's related to #2

**Comment by asimonv** [comment]
@serejahh Yes! It's related with the usage of UIImage+ImageEffect instead of ```UIVisualEffectView```. 

Maybe here's the solution to the iOS 10 bug that you mentioned in #2 :
-> http://stackoverflow.com/questions/39595047/uivisualeffectview-with-mask-layer
